name: foodu
description: "T Foodu - Food Delivery App"
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  gap: ^3.0.1
  intl: ^0.18.1
  logger: ^2.0.1
  ripple_wave: ^0.1.4
  slide_to_act: ^2.0.2
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  country_code_picker: ^3.0.0
  flutter_native_splash : ^2.3.2
  smooth_page_indicator: ^1.2.0+3


  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5


  # Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/navigation_bar/
    - assets/images/on_boarding_images/
    - assets/images/welcome/
    - assets/images/let_you_in/
    - assets/images/profile/
    - assets/images/discount/
    - assets/images/category/
    - assets/images/food/
    - assets/images/search/
    - assets/images/restaurent/
    - assets/images/map/


  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
    - family: Luckiest Guy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
          weight: 400